//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("invoiceDBModel", "Article_InvoiceArticle", "Invoice", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Invoice.Model.Invoice), "Article", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Invoice.Model.Article), true)]

#endregion

namespace Invoice.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class invoiceDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new invoiceDBEntities object using the connection string found in the 'invoiceDBEntities' section of the application configuration file.
        /// </summary>
        public invoiceDBEntities() : base("name=invoiceDBEntities", "invoiceDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new invoiceDBEntities object.
        /// </summary>
        public invoiceDBEntities(string connectionString) : base(connectionString, "invoiceDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new invoiceDBEntities object.
        /// </summary>
        public invoiceDBEntities(EntityConnection connection) : base(connection, "invoiceDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Article> Articles
        {
            get
            {
                if ((_Articles == null))
                {
                    _Articles = base.CreateObjectSet<Article>("Articles");
                }
                return _Articles;
            }
        }
        private ObjectSet<Article> _Articles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Invoice> Invoices
        {
            get
            {
                if ((_Invoices == null))
                {
                    _Invoices = base.CreateObjectSet<Invoice>("Invoices");
                }
                return _Invoices;
            }
        }
        private ObjectSet<Invoice> _Invoices;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Param> Params
        {
            get
            {
                if ((_Params == null))
                {
                    _Params = base.CreateObjectSet<Param>("Params");
                }
                return _Params;
            }
        }
        private ObjectSet<Param> _Params;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Articles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticles(Article article)
        {
            base.AddObject("Articles", article);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Invoices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInvoices(Invoice invoice)
        {
            base.AddObject("Invoices", invoice);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Params EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToParams(Param param)
        {
            base.AddObject("Params", param);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="invoiceDBModel", Name="Article")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Article : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Article object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="invoiceId">Initial value of the InvoiceId property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        /// <param name="netAmount">Initial value of the NetAmount property.</param>
        /// <param name="tax">Initial value of the Tax property.</param>
        /// <param name="taxRate">Initial value of the TaxRate property.</param>
        /// <param name="taxAmount">Initial value of the TaxAmount property.</param>
        /// <param name="grossAmount">Initial value of the GrossAmount property.</param>
        public static Article CreateArticle(global::System.Int32 id, global::System.Int32 invoiceId, global::System.Int32 quantity, global::System.Decimal price, global::System.Decimal netAmount, global::System.Decimal tax, global::System.Double taxRate, global::System.Double taxAmount, global::System.Decimal grossAmount)
        {
            Article article = new Article();
            article.Id = id;
            article.InvoiceId = invoiceId;
            article.Quantity = quantity;
            article.Price = price;
            article.NetAmount = netAmount;
            article.Tax = tax;
            article.TaxRate = taxRate;
            article.TaxAmount = taxAmount;
            article.GrossAmount = grossAmount;
            return article;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InvoiceId
        {
            get
            {
                return _InvoiceId;
            }
            set
            {
                OnInvoiceIdChanging(value);
                ReportPropertyChanging("InvoiceId");
                _InvoiceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvoiceId");
                OnInvoiceIdChanged();
            }
        }
        private global::System.Int32 _InvoiceId;
        partial void OnInvoiceIdChanging(global::System.Int32 value);
        partial void OnInvoiceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ArtName
        {
            get
            {
                return _ArtName;
            }
            set
            {
                OnArtNameChanging(value);
                ReportPropertyChanging("ArtName");
                _ArtName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ArtName");
                OnArtNameChanged();
            }
        }
        private global::System.String _ArtName;
        partial void OnArtNameChanging(global::System.String value);
        partial void OnArtNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Units
        {
            get
            {
                return _Units;
            }
            set
            {
                OnUnitsChanging(value);
                ReportPropertyChanging("Units");
                _Units = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Units");
                OnUnitsChanged();
            }
        }
        private global::System.String _Units;
        partial void OnUnitsChanging(global::System.String value);
        partial void OnUnitsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Int32 _Quantity;
        partial void OnQuantityChanging(global::System.Int32 value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NetAmount
        {
            get
            {
                return _NetAmount;
            }
            set
            {
                OnNetAmountChanging(value);
                ReportPropertyChanging("NetAmount");
                _NetAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NetAmount");
                OnNetAmountChanged();
            }
        }
        private global::System.Decimal _NetAmount;
        partial void OnNetAmountChanging(global::System.Decimal value);
        partial void OnNetAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Tax
        {
            get
            {
                return _Tax;
            }
            set
            {
                OnTaxChanging(value);
                ReportPropertyChanging("Tax");
                _Tax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tax");
                OnTaxChanged();
            }
        }
        private global::System.Decimal _Tax;
        partial void OnTaxChanging(global::System.Decimal value);
        partial void OnTaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double TaxRate
        {
            get
            {
                return _TaxRate;
            }
            set
            {
                OnTaxRateChanging(value);
                ReportPropertyChanging("TaxRate");
                _TaxRate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TaxRate");
                OnTaxRateChanged();
            }
        }
        private global::System.Double _TaxRate;
        partial void OnTaxRateChanging(global::System.Double value);
        partial void OnTaxRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double TaxAmount
        {
            get
            {
                return _TaxAmount;
            }
            set
            {
                OnTaxAmountChanging(value);
                ReportPropertyChanging("TaxAmount");
                _TaxAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TaxAmount");
                OnTaxAmountChanged();
            }
        }
        private global::System.Double _TaxAmount;
        partial void OnTaxAmountChanging(global::System.Double value);
        partial void OnTaxAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal GrossAmount
        {
            get
            {
                return _GrossAmount;
            }
            set
            {
                OnGrossAmountChanging(value);
                ReportPropertyChanging("GrossAmount");
                _GrossAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GrossAmount");
                OnGrossAmountChanged();
            }
        }
        private global::System.Decimal _GrossAmount;
        partial void OnGrossAmountChanging(global::System.Decimal value);
        partial void OnGrossAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CdNumber
        {
            get
            {
                return _CdNumber;
            }
            set
            {
                OnCdNumberChanging(value);
                ReportPropertyChanging("CdNumber");
                _CdNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CdNumber");
                OnCdNumberChanged();
            }
        }
        private global::System.String _CdNumber;
        partial void OnCdNumberChanging(global::System.String value);
        partial void OnCdNumberChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("invoiceDBModel", "Article_InvoiceArticle", "Invoice")]
        public Invoice Invoice
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Invoice>("invoiceDBModel.Article_InvoiceArticle", "Invoice").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Invoice>("invoiceDBModel.Article_InvoiceArticle", "Invoice").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Invoice> InvoiceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Invoice>("invoiceDBModel.Article_InvoiceArticle", "Invoice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Invoice>("invoiceDBModel.Article_InvoiceArticle", "Invoice", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="invoiceDBModel", Name="Invoice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Invoice : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Invoice object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Invoice CreateInvoice(global::System.Int32 id)
        {
            Invoice invoice = new Invoice();
            invoice.Id = id;
            return invoice;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InvoiceNum
        {
            get
            {
                return _InvoiceNum;
            }
            set
            {
                OnInvoiceNumChanging(value);
                ReportPropertyChanging("InvoiceNum");
                _InvoiceNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InvoiceNum");
                OnInvoiceNumChanged();
            }
        }
        private global::System.String _InvoiceNum;
        partial void OnInvoiceNumChanging(global::System.String value);
        partial void OnInvoiceNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> InvoiceDate
        {
            get
            {
                return _InvoiceDate;
            }
            set
            {
                OnInvoiceDateChanging(value);
                ReportPropertyChanging("InvoiceDate");
                _InvoiceDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvoiceDate");
                OnInvoiceDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _InvoiceDate;
        partial void OnInvoiceDateChanging(Nullable<global::System.DateTime> value);
        partial void OnInvoiceDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SupplierName
        {
            get
            {
                return _SupplierName;
            }
            set
            {
                OnSupplierNameChanging(value);
                ReportPropertyChanging("SupplierName");
                _SupplierName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SupplierName");
                OnSupplierNameChanged();
            }
        }
        private global::System.String _SupplierName;
        partial void OnSupplierNameChanging(global::System.String value);
        partial void OnSupplierNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SupplierAddr
        {
            get
            {
                return _SupplierAddr;
            }
            set
            {
                OnSupplierAddrChanging(value);
                ReportPropertyChanging("SupplierAddr");
                _SupplierAddr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SupplierAddr");
                OnSupplierAddrChanged();
            }
        }
        private global::System.String _SupplierAddr;
        partial void OnSupplierAddrChanging(global::System.String value);
        partial void OnSupplierAddrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SupplierINN
        {
            get
            {
                return _SupplierINN;
            }
            set
            {
                OnSupplierINNChanging(value);
                ReportPropertyChanging("SupplierINN");
                _SupplierINN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SupplierINN");
                OnSupplierINNChanged();
            }
        }
        private global::System.String _SupplierINN;
        partial void OnSupplierINNChanging(global::System.String value);
        partial void OnSupplierINNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SupplierKPP
        {
            get
            {
                return _SupplierKPP;
            }
            set
            {
                OnSupplierKPPChanging(value);
                ReportPropertyChanging("SupplierKPP");
                _SupplierKPP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SupplierKPP");
                OnSupplierKPPChanged();
            }
        }
        private global::System.String _SupplierKPP;
        partial void OnSupplierKPPChanging(global::System.String value);
        partial void OnSupplierKPPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeliverFrom
        {
            get
            {
                return _DeliverFrom;
            }
            set
            {
                OnDeliverFromChanging(value);
                ReportPropertyChanging("DeliverFrom");
                _DeliverFrom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeliverFrom");
                OnDeliverFromChanged();
            }
        }
        private global::System.String _DeliverFrom;
        partial void OnDeliverFromChanging(global::System.String value);
        partial void OnDeliverFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeliverTo
        {
            get
            {
                return _DeliverTo;
            }
            set
            {
                OnDeliverToChanging(value);
                ReportPropertyChanging("DeliverTo");
                _DeliverTo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeliverTo");
                OnDeliverToChanged();
            }
        }
        private global::System.String _DeliverTo;
        partial void OnDeliverToChanging(global::System.String value);
        partial void OnDeliverToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrderNum
        {
            get
            {
                return _OrderNum;
            }
            set
            {
                OnOrderNumChanging(value);
                ReportPropertyChanging("OrderNum");
                _OrderNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrderNum");
                OnOrderNumChanged();
            }
        }
        private global::System.String _OrderNum;
        partial void OnOrderNumChanging(global::System.String value);
        partial void OnOrderNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                OnOrderDateChanging(value);
                ReportPropertyChanging("OrderDate");
                _OrderDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderDate");
                OnOrderDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _OrderDate;
        partial void OnOrderDateChanging(Nullable<global::System.DateTime> value);
        partial void OnOrderDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerAddr
        {
            get
            {
                return _CustomerAddr;
            }
            set
            {
                OnCustomerAddrChanging(value);
                ReportPropertyChanging("CustomerAddr");
                _CustomerAddr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerAddr");
                OnCustomerAddrChanged();
            }
        }
        private global::System.String _CustomerAddr;
        partial void OnCustomerAddrChanging(global::System.String value);
        partial void OnCustomerAddrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerINN
        {
            get
            {
                return _CustomerINN;
            }
            set
            {
                OnCustomerINNChanging(value);
                ReportPropertyChanging("CustomerINN");
                _CustomerINN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerINN");
                OnCustomerINNChanged();
            }
        }
        private global::System.String _CustomerINN;
        partial void OnCustomerINNChanging(global::System.String value);
        partial void OnCustomerINNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerKPP
        {
            get
            {
                return _CustomerKPP;
            }
            set
            {
                OnCustomerKPPChanging(value);
                ReportPropertyChanging("CustomerKPP");
                _CustomerKPP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerKPP");
                OnCustomerKPPChanged();
            }
        }
        private global::System.String _CustomerKPP;
        partial void OnCustomerKPPChanging(global::System.String value);
        partial void OnCustomerKPPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OpCode
        {
            get
            {
                return _OpCode;
            }
            set
            {
                OnOpCodeChanging(value);
                ReportPropertyChanging("OpCode");
                _OpCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OpCode");
                OnOpCodeChanged();
            }
        }
        private global::System.String _OpCode;
        partial void OnOpCodeChanging(global::System.String value);
        partial void OnOpCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OptionField
        {
            get
            {
                return _OptionField;
            }
            set
            {
                OnOptionFieldChanging(value);
                ReportPropertyChanging("OptionField");
                _OptionField = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OptionField");
                OnOptionFieldChanged();
            }
        }
        private global::System.String _OptionField;
        partial void OnOptionFieldChanging(global::System.String value);
        partial void OnOptionFieldChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("invoiceDBModel", "Article_InvoiceArticle", "Article")]
        public EntityCollection<Article> Articles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Article>("invoiceDBModel.Article_InvoiceArticle", "Article");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Article>("invoiceDBModel.Article_InvoiceArticle", "Article", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="invoiceDBModel", Name="Param")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Param : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Param object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Param CreateParam(global::System.Int32 id)
        {
            Param param = new Param();
            param.Id = id;
            return param;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SupplierName
        {
            get
            {
                return _SupplierName;
            }
            set
            {
                OnSupplierNameChanging(value);
                ReportPropertyChanging("SupplierName");
                _SupplierName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SupplierName");
                OnSupplierNameChanged();
            }
        }
        private global::System.String _SupplierName;
        partial void OnSupplierNameChanging(global::System.String value);
        partial void OnSupplierNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SupplierAddr
        {
            get
            {
                return _SupplierAddr;
            }
            set
            {
                OnSupplierAddrChanging(value);
                ReportPropertyChanging("SupplierAddr");
                _SupplierAddr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SupplierAddr");
                OnSupplierAddrChanged();
            }
        }
        private global::System.String _SupplierAddr;
        partial void OnSupplierAddrChanging(global::System.String value);
        partial void OnSupplierAddrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SupplierINN
        {
            get
            {
                return _SupplierINN;
            }
            set
            {
                OnSupplierINNChanging(value);
                ReportPropertyChanging("SupplierINN");
                _SupplierINN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SupplierINN");
                OnSupplierINNChanged();
            }
        }
        private global::System.String _SupplierINN;
        partial void OnSupplierINNChanging(global::System.String value);
        partial void OnSupplierINNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SupplierKPP
        {
            get
            {
                return _SupplierKPP;
            }
            set
            {
                OnSupplierKPPChanging(value);
                ReportPropertyChanging("SupplierKPP");
                _SupplierKPP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SupplierKPP");
                OnSupplierKPPChanged();
            }
        }
        private global::System.String _SupplierKPP;
        partial void OnSupplierKPPChanging(global::System.String value);
        partial void OnSupplierKPPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeliverFrom
        {
            get
            {
                return _DeliverFrom;
            }
            set
            {
                OnDeliverFromChanging(value);
                ReportPropertyChanging("DeliverFrom");
                _DeliverFrom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeliverFrom");
                OnDeliverFromChanged();
            }
        }
        private global::System.String _DeliverFrom;
        partial void OnDeliverFromChanging(global::System.String value);
        partial void OnDeliverFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InvNumPref
        {
            get
            {
                return _InvNumPref;
            }
            set
            {
                OnInvNumPrefChanging(value);
                ReportPropertyChanging("InvNumPref");
                _InvNumPref = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InvNumPref");
                OnInvNumPrefChanged();
            }
        }
        private global::System.String _InvNumPref;
        partial void OnInvNumPrefChanging(global::System.String value);
        partial void OnInvNumPrefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> InvNumCnt
        {
            get
            {
                return _InvNumCnt;
            }
            set
            {
                OnInvNumCntChanging(value);
                ReportPropertyChanging("InvNumCnt");
                _InvNumCnt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvNumCnt");
                OnInvNumCntChanged();
            }
        }
        private Nullable<global::System.Int32> _InvNumCnt;
        partial void OnInvNumCntChanging(Nullable<global::System.Int32> value);
        partial void OnInvNumCntChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> InvNumYear
        {
            get
            {
                return _InvNumYear;
            }
            set
            {
                OnInvNumYearChanging(value);
                ReportPropertyChanging("InvNumYear");
                _InvNumYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvNumYear");
                OnInvNumYearChanged();
            }
        }
        private Nullable<global::System.Int16> _InvNumYear;
        partial void OnInvNumYearChanging(Nullable<global::System.Int16> value);
        partial void OnInvNumYearChanged();

        #endregion

    
    }

    #endregion

    
}
